### ISSUE TITLE
Renaming new file with old file shows old file preview

### ISSUE THREAD

**Issue by harishnkr** [NikitaIvanovV/ctpv#46] opened 2023-03-13 17:53 UTC
![simplescreenrecorder-2023-03-13_23 11 32](https://user-images.githubusercontent.com/48408097/224786571-2d440892-916e-458f-9adf-594866952791.gif)

**Comment by NikitaIvanovV** [comment] 2023-03-16 20:37
Looks like a duplicate of #45

**Closed by NikitaIvanovV** 2023-03-16 20:37 UTC
